# Generated by Django 5.1.15 on 2026-05-30 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsetting'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guarantor',
            name='unique_merchant_guarantor',
        ),
        migrations.RemoveConstraint(
            model_name='guarantor',
            name='merchant_cannot_guarantee_self',
        ),
        migrations.AddField(
            model_name='guarantor',
            name='guarantor_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='relation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantees_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='guarantor',
            constraint=models.UniqueConstraint(condition=models.Q(('guarantor__isnull', False)), fields=('merchant', 'guarantor'), name='unique_merchant_guarantor'),
        ),
        migrations.AddConstraint(
            model_name='guarantor',
            constraint=models.CheckConstraint(condition=models.Q(('guarantor__isnull', True), models.Q(('merchant', models.F('guarantor')), _negated=True), _connector='OR'), name='merchant_cannot_guarantee_self'),
        ),
    ]
